name: Branch Names
description: Retrieve github branch or tag information without the /ref/* prefix
author: n-nikitins
inputs:
  strip_tag_prefix:
    description: 'The tag prefix to strip i.e v0.0.1 -> (strip v) -> 0.0.1'
    default: ''
    required: false

outputs:
  is_default:
    value: ${{ steps.default.outputs.is_default }}
    description: 'Returns "true" if the current branch is the default else "false".'
  is_tag:
    value: ${{ steps.tag.outputs.is_tag }}
    description: 'Returns "true" if the current branch is a tag else "false".'
  current_branch:
    value: ${{ steps.current_branch.outputs.current_branch }}
    description: 'Returns the value of the current branch which is consistent regardless of event_type: i.e (push, pull_requests).'
  base_ref_branch:
    value: ${{ steps.branch.outputs.base_ref_branch }}
    description: 'The target branch of a pull request'
  head_ref_branch:
    value: ${{ steps.branch.outputs.head_ref_branch }}
    description: 'The source branch of a pull request'
  ref_branch:
    value: ${{ steps.branch.outputs.ref_branch }}
    description: 'The branch that triggered the workflow run.'
  tag:
    value: ${{ steps.tag.outputs.tag }}
    description: 'The tag that triggered the workflow run.'

runs:
  using: "composite"
  steps:
  
    - shell: pwsh
      run: |
        echo ${{github.ref}}
        $base_ref = "${${{github.base_ref}}}"
        $head_red = "${${{github.head_ref}}}"
        $event_name = "${${{github.event_name}}}"
        
        if ($base_ref -eq '') { Write-Host "variable is null" }
        if ($head_red -eq '') { Write-Host "variable is null" }
        if ($event_name -eq '') { Write-Host "variable is null" }
      
    - id: branch
      run: .\.github\workflows\composite-actions-windows\powershell-scripts\branch.ps1 -github_ref ${{ github.ref}} -github_base_ref ${{ github.base_ref}} -github_head_ref ${{ github.head_ref }}
      shell: powershell
      
    - id: current_branch
      run: .\.github\workflows\composite-actions-windows\powershell-scripts\current_branch.ps1 -github_ref ${{ github.ref}} -github_event_name ${{ github.event_name }} -head_ref_branch ${{ steps.branch.outputs.head_ref_branch }} -ref_branch ${{ steps.branch.outputs.ref_branch }} -strip_tag_prefix ${{ inputs.strip_tag_prefix }}
      shell: powershell
      
    - id: default
      run: .\.github\workflows\composite-actions-windows\powershell-scripts\default.ps1 -github_ref ${{ github.ref}} -current_branch ${{ steps.current_branch.outputs.current_branch }} -ref_branch ${{ steps.branch.outputs.ref_branch }}
      shell: powershell
      
    - id: tag
      run: .\.github\workflows\composite-actions-windows\powershell-scripts\tag.ps1 -github_ref ${{ github.ref}} -strip_tag_prefix ${{ inputs.strip_tag_prefix }}
      shell: powershell
